server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  # JPA
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/studier?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver